@startuml rfc0014-01-aanvragen_autorisatie
' !pragma teoz true

skinparam ParticipantPadding 20
skinparam BoxPadding 10

box "Deelnemer"
    participant "Client" as Client
end box

box "nID"
    participant "autorisatieserver" as AuthzServer
    participant "PEP" as PEP
    participant "PDP" as PDP
end box

box "Register"
    participant "Resource-Server" as resourceserver
end box

autonumber "<b>[000]"
activate Client
    Client -> AuthzServer: **Aanvragen van autorisatie**\n"scope": "registers/resource:read"\n Authenticatiemiddel
    activate AuthzServer
        AuthzServer -> AuthzServer: Valideer Authenticatiemiddel
        AuthzServer -> AuthzServer: Run Rule-engine o.b.v. scope(s)
        activate AuthzServer #LightGray
            AuthzServer -> AuthzServer: Valideer autorisatie
            AuthzServer -> AuthzServer: Genereer JWT Access-Token
            activate AuthzServer #DarkGray
            deactivate AuthzServer
        deactivate AuthzServer
        AuthzServer --> Client --: 200 Response (JWT Access-Token)
    deactivate AuthzServer
deactivate Client


Client -> PEP: **GraphQL Request**\nAuthenticatiemiddel + JWT Access-Token + Query 
activate Client


    activate PEP
    note right of PEP: Inline filtering requests

    PEP -> PEP: Valideer Authenticatiemiddel
    PEP -> PEP: Valideer Access-Token
    PEP -> PDP: Query met policy valideren
        activate PEP #LightGray
            activate PDP
                PDP -> PDP: Valideer query
                PDP -> PDP: Verify context information    
                PDP -> PEP: Query allowed
            deactivate PDP
            PEP -> resourceserver: GraphQL Request
        deactivate PEP

        activate resourceserver
            resourceserver --> PEP: 200 Response (GraphQL)
        deactivate resourceserver
    
    PEP --> Client: 200 Response (GraphQL)
    deactivate PEP

deactivate Client

@enduml
