@startuml rfc0008-04-error-flow
title notificatie flow incl. nID
skinparam handwritten false
skinparam participantpadding 20
skinparam boxpadding 40


box bronhouder #lightblue
  participant "Resource" as Resource
  participant "Register- \ndata" as Register
end box

box "nID"
    participant "autorisatieserver" as AuthzServer
    participant "PEP" as PEP
    participant "PDP" as PDP
end box


box deelnemer #lightyellow
  participant "Resource-\nServer" as ResServer
end box

note over PEP #lightgreen: Het autorisatie en validatie-proces \nis beschreven in RFC0014 \nFunctionele uitwerking aanvragen autorisatie \n(oAuth2.0) 

Resource -> Register : registratie data

activate Resource 
  activate Register
  Register -> Register: event trigger
  Register -> Resource : bepaal notificatietype
  deactivate Register

  Resource -> Resource: genereer GraphQL notificatie

  Resource -> AuthzServer: **Aanvragen van autorisatie**\n"scope": "../notificaties/notificatie:create" 
    activate AuthzServer #Darkgrey
        AuthzServer --> Resource --: 200 Response (JWT Access-Token) 
    deactivate AuthzServer

  Resource -> PEP: **GraphQL Request **\nAuthenticatiemiddel + JWT Access-Token + notificatie
  activate PEP

    PEP -> PEP: Valideer Authenticatie en \nAccess
    PEP -> PDP: GraphQL met policy valideren
      activate PEP #LightGray
        activate PDP
        PDP -> PDP: Valideer graphql  
        autonumber "<color:red><b>[00]"
          Resource <-[#red]-X PDP: <color:red> 400 Bad Request
          Resource <-[#red]-X PDP: <color:red> 400 Bad Request: GRAPHQL_VALIDATION_FAILED       
        autonumber stop
          PDP -> PEP: Graphql allowed
        deactivate PDP
        PEP -> ResServer: **GraphQL Request**
      deactivate PEP

    activate ResServer
    ResServer -> ResServer: ontvang notificatie
    ResServer --> PEP: GraphQL 200 response
    deactivate ResServer
    PEP --> Resource: GraphQL 200 response

  note over PDP, ResServer #pink: Er komt een nieuwe RFC voor \nfoutafhandeling door de GraphQL-server

    deactivate PEP 
    Resource --> Resource: verwerk GraphQL 200 response

  @enduml