@startuml rfc0014-2-foutmeldingen_overzicht
' !pragma teoz true

skinparam ParticipantPadding 20
skinparam BoxPadding 10

box "Deelnemer"
    participant "Client" as Client
end box

box "nID"
    participant "autorisatieserver" as AuthzServer
    participant "PEP" as Filter
end box

box "Register"
    participant "Resource-Server" as resourceserver
end box



Client -> AuthzServer: <b>[001] **Aanvragen van autorisatie**\n"scope": "registers/resource:read"\n Authenticatiemiddel
activate Client
activate AuthzServer


autonumber "<color:red><b>[00]"
Client <-[#red]-X AuthzServer:<color:red> 400 Audience Required
Client <-[#red]-X AuthzServer:<color:red> 401 Unauthorized
Client <-[#red]-X AuthzServer:<color:red> 403 Not Allowed
Client <-[#red]-X AuthzServer:<color:red> 403 Invalid client certificate
Client <-[#red]-X AuthzServer:<color:red> 404 Not found
Client <-[#red]-X AuthzServer:<color:red> 500 Internal Server Error
autonumber stop



AuthzServer -> AuthzServer: <b>[002] Valideer Authenticatiemiddel
AuthzServer -> AuthzServer: <b>[003] Run Rule-engine o.b.v. scope(s)
AuthzServer --> Client --: <b>[004] 200 Response (Access-Token)
deactivate AuthzServer
deactivate Client

Client -> Filter: <b>[005] **GraphQL Request**\nAuthenticatiemiddel + Access-Token + query
activate Client
activate Filter
note right of Filter: Inline filtering requests

autonumber resume
    Client <-[#red]-X Filter: <color:red> 400 Invalid Query Syntax
    Client <-[#red]-X Filter: <color:red> 400 No operation
    Client <-[#red]-X Filter: <color:red> 400 Invalid scope
    Client <-[#red]-X Filter: <color:red> 401 Unauthorized
    Client <-[#red]-X Filter: <color:red> 403 Invallid Client Certificate
    Client <-[#red]-X Filter: <color:red> 403 Not Allowed
    Client <-[#red]-X Filter: <color:red> 403 Policy Acces Denied
    Client <-[#red]-X Filter: <color:red> 403 Request does not match scopes
    Client <-[#red]-X Filter: <color:red> 500 Internal server error
    Client <-[#red]-X Filter: <color:red> 502 Bad gateway
    Client <-[#red]-X Filter: <color:red> 504 Gateway timeout
autonumber stop


Filter -> resourceserver: <b>[006] GraphQL Request
activate resourceserver
resourceserver --> Filter: <b>[007] 200 Response (GraphQL)
deactivate resourceserver

Filter --> Client: <b>[008] 200 Response (GraphQL)
deactivate Filter
deactivate Client

@enduml