@startuml rfc008-02-notificatie_sequence
title notificatie sequence-diagram
skinparam handwritten false
skinparam participantpadding 20
skinparam boxpadding 40

box bronhouder #lightblue
  participant "Resource" as Resource
  participant "Register- \ndata" as Register
end box

box "nID"
    participant "autorisatieserver" as AuthzServer
    participant "PEP" as PEP
    participant "PDP" as PDP
end box

box deelnemer #lightyellow
  participant "Resource-\nServer" as ResServer
end box

note over PEP #lightgreen: Het autorisatie en validatie-proces \nis beschreven in RFC0014 \nFunctionele uitwerking aanvragen autorisatie \n(oAuth2.0) 
autonumber "<b>[00]"
Resource -> Register : <b>registratie data

activate Resource 
  activate Register
  Register -> Register: <b>event trigger
  Register -> Resource : <b>bepaal notificatietype
  deactivate Register

  Resource -> Resource: <b>genereer GraphQL notificatie
autonumber stop
  Resource -> AuthzServer: Aanvragen van autorisatie\n"scope": "../notificaties/notificatie:create" 
    activate AuthzServer #Darkgrey
        AuthzServer --> Resource --: 200 Response (JWT Access-Token) 
    deactivate AuthzServer
autonumber resume
  Resource -> PEP: **GraphQL Request **\nAuthenticatiemiddel + JWT Access-Token + notificatie

autonumber stop
  activate PEP

    PEP -> PEP: Valideer Authenticatie en \nAccess
    PEP -> PDP: GraphQL met policy valideren
      activate PEP #LightGray
        activate PDP
        PDP -> PDP: Valideer graphql    
        autonumber stop
          PDP -> PEP: Graphql allowed
        deactivate PDP
        PEP -> ResServer: **[05] GraphQL Request**
      deactivate PEP

autonumber resume
    activate ResServer
    ResServer -> ResServer: <b>ontvang \n<b>notificatie
    ResServer --> PEP: <b>GraphQL 200 response
    deactivate ResServer
autonumber stop
    PEP --> Resource: <b>[07] GraphQL 200 response


    deactivate PEP 
    Resource --> Resource: <b>[08] verwerk GraphQL 200 response

  @enduml