@startuml rfc008-03-foutmelden-errors
title melding sequence-diagram + error
skinparam handwritten false
skinparam participantpadding 20
skinparam boxpadding 20

box deelnemer #lightyellow
  participant "Resource" as Resource
end box

box "nID"
  participant "autorisatieserver" as AuthzServer
  participant "PEP" as PEP
  participant "PDP" as PDP
end box

box bronhouder #lightblue
  participant "Resource-\nServer" as ResServer
end box

note over PEP #lightgreen: Het autorisatie en validatie-proces \nis beschreven in RFC0014 \nFunctionele uitwerking aanvragen autorisatie \n(oAuth2.0) 


ResServer o-> Resource: <b>ontvang data uit register
activate Resource 
  Resource -> Resource: <b>valideer data
  Resource -x Resource : <b>bepaal foutcode
  Resource -> Resource: <b>genereer GraphQL foutmelding

  Resource -> AuthzServer: Aanvragen van autorisatie\n"scope": "..meldingen/melding:create" 
    activate AuthzServer #Darkgrey
        AuthzServer --> Resource --: 200 Response (JWT Access-Token) 
    deactivate AuthzServer
  Resource -> PEP: **GraphQL Request **\nAuthenticatiemiddel + JWT Access-Token + foutmelding

  activate PEP #Darkgrey

  PEP -> PEP: Valideer Authenticatie en \nAccess
  PEP -> PDP: GraphQL met policy valideren
    activate PEP #Darkgrey
      activate PDP #Darkgrey
      PDP -> PDP: Valideer graphql
        autonumber "<color:red><b>[00]"
          Resource <-[#red]-X PDP: <color:red> 400 Bad Request
          Resource <-[#red]-X PDP: <color:red> 400 Bad Request: GRAPHQL_VALIDATION_FAILED       
        autonumber stop

        PDP --> PEP: Graphql allowed
      deactivate PDP
      PEP -> ResServer: **[05] GraphQL Request**
    deactivate PEP

    activate ResServer
    ResServer -> ResServer: <b>ontvang \n<b>melding
    ResServer --> PEP: <b>GraphQL 200 response
    deactivate ResServer
    note over PDP, ResServer #pink: Er komt een nieuwe RFC voor \nfoutafhandeling door de GraphQL-server
    PEP --> Resource: GraphQL 200 response
    deactivate PEP 
    Resource --> Resource: verwerk GraphQL 200 response

  @enduml