@startuml rfc0018-02-foutmelden
skinparam handwritten false
skinparam participantpadding 20
skinparam boxpadding 40
autonumber "<b>[00]"
box bronhouder #lightblue
participant "Register" as brs
participant "Register-data" as rg
participant "Netwerkpunt" as bnp 
end box

box deelnemer #lightyellow
participant "Resource" as rsrc
end box

rg o-> rsrc: raadpleging
    activate rsrc

group fout melden
    rsrc -> rsrc: iWlz-Fout \ngeconstateerd
    rsrc -> bnp: iWlz-Foutmelding naar \nbronhouder
    activate bnp
    bnp -> bnp: valideer inzending
    bnp -> brs: doorzetten iWlz-foutmelding
    activate brs
    brs -> bnp: return response {204}
    deactivate brs
    bnp -> rsrc: return response {204}

    alt #Pink
      bnp --> rsrc: response: {400} ongeldig verzoek
      deactivate bnp
      deactivate rsrc
    end alt

end

@enduml