  @startuml rfc008-02-notificatie_sequence
  title notificatie sequence-diagram
  skinparam handwritten false
  skinparam participantpadding 20
  skinparam boxpadding 40
  autonumber "<b>[00]"
  box bronhouder #lightblue
  participant "Backoffice" as bs
  end box

  box adresboek
  participant "Adresboek" as ab
  end box

  box deelnemer #lightyellow
  participant "Backoffice" as dnp
  end box

    bs -> ab : publiceer adresgegevens
    activate ab
    activate bs
ab -> bs : response
    deactivate bs
deactivate ab
