@startuml rfc0018-02-foutmelden
skinparam handwritten false
skinparam participantpadding 20
skinparam boxpadding 40
autonumber "<b>[00]"
box bronhouder #lightblue
participant "Backoffice" as bs
participant "Register" as rg
participant "Netwerkpunt" as bnp 
end box

box deelnemer #lightyellow
participant "Netwerkpunt" as dnp
participant "Backoffice" as dbs
end box

rg o-> dbs: raadpleging
    activate dbs

group fout melden
    dbs -> dbs: iWlz-Fout \ngeconstateerd
    dbs -> dnp: iWlz-Foutmelding verzenden
    activate dnp
    dnp -> bnp: iWlz-Foutmelding naar \nbronhouder
    activate bnp
    bnp -> bnp: valideer inzending
    bnp -> bs: doorzetten iWlz-foutmelding
    activate bs
    bs -> bnp: return response {204}
    deactivate bs
    bnp -> dnp: return response {204}
    dnp -> dbs: return response {204}

    alt #Pink
      bnp --> dnp: response: {400} ongeldig verzoek
      deactivate bnp
      dnp --> dbs: response: {400} ongeldig verzoek
      deactivate dnp
      deactivate dbs
    end alt

end

@enduml