@startuml rfc0014-01-aanvragen_autorisatie
' !pragma teoz true

skinparam ParticipantPadding 20
skinparam BoxPadding 10

box "Deelnemer"
    participant "Client" as Client
end box

box "nID"
    participant "autorisatieserver" as AuthzServer
    participant "PEP" as PEP
    participant "PDP" as PDP
    participant "PRP" as PRP
    participant "Resource-server" as nIDResourceServer
end box

box "Register"
    participant "PIP" as PIP
    participant "Resource" as BEMRegister
end box

autonumber "<b>[000]"
activate Client
    Client -> AuthzServer: **Aanvragen van autorisatie**\n"scope": "registers/resource:read"\n Authenticatiemiddel
    activate AuthzServer
        AuthzServer -> AuthzServer: Valideer Authenticatiemiddel
        AuthzServer -> AuthzServer: Run Rule-engine o.b.v. scope(s)
        activate AuthzServer #LightGray
            AuthzServer -> AuthzServer: Valideer autorisatie
            AuthzServer -> AuthzServer: Genereer JWT Access-Token
            activate AuthzServer #DarkGray
            deactivate AuthzServer
        deactivate AuthzServer
        AuthzServer --> Client --: 200 Response (JWT Access-Token)
    deactivate AuthzServer
deactivate Client


Client -> nIDResourceServer: **GraphQL Request**\nAuthenticatiemiddel + JWT Access-Token + Query 
activate Client

activate nIDResourceServer
    activate PEP
    note right of PEP: Inline filtering requests

    PEP -> PEP: Valideer Authenticatiemiddel
    PEP -> PEP: Valideer Access-Token
    PEP -> PDP: Valideer Query met policy
            activate PDP
            PDP -> PRP: Haal relevante policy op
                    activate PRP
                    PRP -> PDP: Policy return
                    deactivate PRP
                    PDP -> PDP: Verify query
                    group optional
                    PDP -> PIP: Verify context information
                        activate PDP #LightGray
                        activate PIP
                        PIP -> PIP: Verify
                        PIP -> PDP: Allow
                        deactivate PDP
                        deactivate PIP
                    end
            PDP -> PEP: Query allow

            deactivate PDP
    
    PEP -> PEP: Valideer GraphQL request met scope(s) 
    note left #Red: IS DEZE STAP NOG NODIG

    nIDResourceServer -> BEMRegister: GraphQL Request
    deactivate PEP

activate BEMRegister

BEMRegister --> nIDResourceServer: 200 Response (GraphQL)
deactivate BEMRegister

nIDResourceServer --> Client: 200 Response (GraphQL)
deactivate nIDResourceServer

deactivate Client

@enduml
